Update montery

diff --git a/installscript b/installscript
--- a/installscript
+++ b/installscript
@@ -7,7 +7,7 @@ touch $HOME/.hushlogin
 echo 'install oh-my-zhs'
 echo '-----------------'
 rm -rf $HOME/.oh-my-zsh
-curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
+sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
 chsh -s $(which zsh)
 
 # symlink bash_profile
@@ -18,10 +18,6 @@ ln -s $HOME/.dotfiles/shell/.bash_profile $HOME/.bash_profile
 rm $HOME/.profile
 ln -s $HOME/.dotfiles/shell/.bash_profile $HOME/.profile
 
-# symlink yarnrc
-rm $HOME/.yarnrc
-ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.yarnrc
-
 # symlink zsh prefs
 rm $HOME/.zshrc
 ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
@@ -30,23 +26,9 @@ ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
 rm $HOME/.vimrc
 ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
 
-# symlink yarn prefs
-rm $HOME/.npmrc
-ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.npmrc
-
 # vim config
 rm -R $HOME/.vim
 ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim
-
-echo 'Install composer'
-echo '----------------'
-cd ~/.dotfiles
-php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-php -r "if (hash_file('sha384', 'composer-setup.php') === '8a6138e2a05a8c28539c9f0fb361159823655d7ad2deecb371b04a83966c61223adc522b0189079e3e9e277cd72b8897') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
-php composer-setup.php
-php -r "unlink('composer-setup.php');"
-echo 'move composer to /usr/local/bin/composer'
-mv -f composer.phar /usr/local/bin/composer
 
 echo 'Install homebrew'
 echo '----------------'
@@ -64,20 +46,6 @@ ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig
 # global gitigore
 ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
 git config --global core.excludesfile $HOME/.global-gitignore
-
-echo 'install wget'
-echo '------------'
-brew install wget --overwrite
-
-echo 'install httpie'
-echo '------------'
-brew install httpie
-
-echo 'install brew-cask'
-echo '------------------'
-brew tap caskroom/cask
-brew install brew-cask
-brew tap caskroom/versions
 
 echo 'install httrack'
 echo '-------------'
@@ -98,12 +66,17 @@ brew install ack
 echo 'Install php'
 echo '-----------'
 brew install php
-brew install php@7.2
-brew install php@7.3
+brew install php@7.4
 
 echo 'Install node'
 echo '-----------'
-brew install node@12
+brew install node
+
+echo 'Configure npm'
+echo '-------------'
+# Create a directory for global packages and tell npm where to store globally installed packages
+mkdir "${HOME}/.npm-packages"
+npm config set prefix "${HOME}/.npm-packages"
 
 echo 'Install zsh-autosuggestions'
 echo '---------------------------'
@@ -113,17 +86,47 @@ echo 'install yarn'
 echo '------------'
 brew install yarn
 
-echo 'install gulp'
-echo '------------'
-npm install -g gulp
-
 echo 'install svgo'
 echo '------------'
 npm install -g svgo
 
-echo 'install system apps'
+echo 'Install composer'
+echo '----------------'
+EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
+php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
+then
+    >&2 echo 'ERROR: Invalid installer checksum'
+    rm composer-setup.php
+    exit 1
+fi
+php composer-setup.php
+rm composer-setup.php
+mkdir -p /usr/local/bin
+mv composer.phar /usr/local/bin/composer
+
+echo 'install valet'
 echo '------------'
-brew cask install --force 1password gitify screaming-frog-seo-spider a-better-finder-rename google-drive-file-stream sketch alfred google-hangouts spotify anydesk google-web-designer sublime-text balenaetcher grammarly tableplus bartender iterm2 teamviewer calibre lingo the-unarchiver craftmanager macdown tower diffmerge mamp vlc docker moom whatsapp dropbox phpstorm xmind evernote poedit zeplin firefox postman
+composer global require laravel/valet
+valet install
+cd ~/Sites
+valet park
+
+echo 'install mailhog'
+echo '------------'
+brew install mailhog
+brew services start mailhog
+valet proxy mailhog.test http://127.0.0.1:8025
+
+echo 'Install some nice quicklook plugins'
+echo '-----------------------------------'
+brew install --cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzip  suspicious-package
+
+
+# echo 'install system apps'
+# echo '------------'
+# brew cask install --force screaming-frog-seo-spider sketch alfred google-hangouts spotify anydesk google-web-designer sublime-text balenaetcher grammarly tableplus bartender iterm2 teamviewer calibre lingo the-unarchiver craftmanager macdown tower diffmerge mamp vlc docker moom whatsapp dropbox phpstorm xmind evernote poedit zeplin firefox postman
 
 echo '++++++++++++++++++++++++++++++'
 echo '++++++++++++++++++++++++++++++'
